### ISSUE TITLE
update to electron version 1.0

### ISSUE THREAD

**Issue by fdu-axiometrics** [NathanWalker/angular-seed-advanced#76]
**Steps to reproduce and a minimal demo of the problem**

update electron-prebuilt to version 1.0.3

and run npm run start.desktop.windows

**Comment by NathanWalker** [comment]
@fdu-axiometrics Is the current version causing you any trouble, just curious?

**Comment by fdu-axiometrics** [comment]
yeah. I actually I found a fix. the electron import changed. not sure if you have already fixed it.

**Comment by NathanWalker** [comment]
Electron import? Is it incorrect on master currently? If you find it to be incorrect here, do you mind submitting a PR with your fix if so?

**Comment by friksa** [comment]
I need Electron upgraded as I need features in Chrome 50.  When I update the Electron version number to 1.2.1, it fails to start up with:

```
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Users/fstrecker/dev-sp/gp6/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/fstrecker/dev-sp/gp6/dist/dev/main.desktop.js:4:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

**Comment by friksa** [comment]
The fix turned out to be super easy :)

One of these days, I will figure out how to do a pull request... until then, here is the solution to upgrade to Electron 1.2.1.

In main.desktop.ts, change this:

```
const app: any = require('app');
const Menu: any = require('menu');
const shell: any = require('shell');
const crashReporter: any = require('crash-reporter');
const BrowserWindow: any = require('browser-window');
```

to

```
const electron = require('electron');
const app = electron.app;
const Menu: any = electron.Menu;
const shell: any = electron.shell;
const {crashReporter} = require('electron');
const BrowserWindow = electron.BrowserWindow;
```

**Comment by NathanWalker** [comment]
Thank you @friksa updated to 1.2.1 on master now 👍
