### ISSUE TITLE
Build error "All declarations of 'WeakMap' must have identical type parameters"

### ISSUE THREAD

**Issue by fourctv** [NathanWalker/angular-seed-advanced#351]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see use [gitter](https://gitter.im/mgechev/angular2-seed) or [stackoverflow](https://stackoverflow.com/questions/tagged/angular2)
```

**Current behavior**

After merging the latest seed I'm now getting a compile error on `lodash` type:
```
/node_modules/@types/lodash/index.d.ts(19449,15): error TS2428: All declarations of 'WeakMap' must have identical type parameters.
```

`@types/lodash` version = 4.14.37

Even if I run `yarn` and bring `@types/lodash` to the latest version (4.14.52), I still get the same error!

(FYI, that error does not affect my app building and running, just a nuisance at this point)

**Expected behavior**
no compile errors

**Minimal reproduction of the problem with instructions**
just do `npm start`

**Please tell us about your environment:**
OS X 11.6, VSCode 1.9.1, tsc 2.1.6

* **Angular Seed Version:** `10c7272`

* **Node:** `node --version` = 7.4.0, `npm` = 4.0.5

**Comment by rernens** [comment]
I am having the same problem for a few weeks now and can't build for prod.

I seems that this issue is affecting a lot of lodash based projects according to search made on Google.

Is there a work around to this ?

**Comment by NathanWalker** [comment]
Have you guys tried this potential solution?:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324#issuecomment-277754823
It does appear to be an issue with lodash.

**Comment by rernens** [comment]
@NathanWalker - 

I have checked that.
I changed the /node_modules/@types/lodash/index.d.ts to reflect the weakmap definition change to comply with TS 2.2

declare global {
    interface Set<T> { }
    interface Map<K, V> { }
    interface WeakSet<T> { }
// interface WeakMap<K, V> {
    interface WeakMap<K extends object, V> { }
}

After that, i could build.prod my project.

**Comment by fourctv** [comment]
@rernens @NathanWalker that works, but changing node_modules is a big no no.

it sure is a workaround to enable prod build, but definitely not a solution.
probably need to wait for a future lodash version that fixes that.

**Comment by nghiado** [comment]
I found a work around here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14324#issuecomment-277738061

@NathanWalker I thought that adding skipLibCheck: true to tsconfig.json should fix the problem but turned out that your script is not using tsconfig.json during production build. Looks like a bug to me?
@fourctv Just copy **build.js.prod.ts** to tools/tasks/project and modify line  22 to add

> skipLibCheck: true

 as tsconfig to **makeTsProject**
`  let tsProject = makeTsProject({ skipLibCheck: true }, Config.TMP_DIR);
`
then it should work

**Comment by llwt** [comment]
@nghiado It does use the tsconfig durning the prod build there are just multiple configs that need to have skipLibCheck added:
```
tsconfig.json
nativescript/tsconfig.json
src/client/tsconfig.json
```

**Comment by NathanWalker** [comment]
I am no longer seeing this on latest master 👍

**Comment by DanielKucal** [comment]
Hi @NathanWalker, I just downloaded this seed and it occurred for me on `gulp build.tns`:
![image](https://cloud.githubusercontent.com/assets/8938562/24972746/d0adec2a-1fbc-11e7-97bb-112f6ca82106.png)
